const SYMBOL_COMPANY_MAP: Record<string, string> = {
  'AAPL': 'apple',
  'MSFT': 'microsoft',
  'GOOGL': 'google',
  'GOOG': 'google',
  'AMZN': 'amazon',
  'META': 'meta',
  'FB': 'meta',
  'TSLA': 'tesla',
  'NVDA': 'nvidia',
  'NFLX': 'netflix',
  'AMD': 'amd',
  'INTC': 'intel',
  'IBM': 'ibm',
  'ORCL': 'oracle',
  'CRM': 'salesforce',
  'ADBE': 'adobe',
  'PYPL': 'paypal',
  'V': 'visa',
  'MA': 'mastercard',
  'JPM': 'jpmorgan',
  'BAC': 'bankofamerica',
  'WFC': 'wellsfargo',
  'GS': 'goldmansachs',
  'MS': 'morganstanley',
  'C': 'citi',
  'UBER': 'uber',
  'LYFT': 'lyft',
  'ABNB': 'airbnb',
  'COIN': 'coinbase',
  'SQ': 'block',
  'SHOP': 'shopify',
  'SNAP': 'snap',
  'PINS': 'pinterest',
  'TWTR': 'twitter',
  'X': 'twitter',
  'DIS': 'disney',
  'WMT': 'walmart',
  'TGT': 'target',
  'COST': 'costco',
  'NKE': 'nike',
  'SBUX': 'starbucks',
  'MCD': 'mcdonalds',
  'KO': 'cocacola',
  'PEP': 'pepsi',
  'JNJ': 'johnsonandjohnson',
  'PFE': 'pfizer',
  'MRNA': 'moderna',
  'CVS': 'cvs',
  'UNH': 'unitedhealthgroup',
  'BA': 'boeing',
  'LMT': 'lockheedmartin',
  'CAT': 'caterpillar',
  'DE': 'johndeere',
  'XOM': 'exxonmobil',
  'CVX': 'chevron',
  'COP': 'conocophillips',
  'GM': 'generalmotors',
  'F': 'ford',
  'TM': 'toyota',
  'RIVN': 'rivian',
  'LCID': 'lucidmotors',
  'NIO': 'nio',
  'PLTR': 'palantir',
  'SNOW': 'snowflake',
  'DDOG': 'datadog',
  'NET': 'cloudflare',
  'ZM': 'zoom',
  'DOCU': 'docusign',
  'TEAM': 'atlassian',
  'WDAY': 'workday',
  'NOW': 'servicenow',
  'PANW': 'paloaltonetworks',
  'CRWD': 'crowdstrike',
  'ZS': 'zscaler',
  'OKTA': 'okta',
  'TWLO': 'twilio',
  'MDB': 'mongodb',
  'DKNG': 'draftkings',
  'RBLX': 'roblox',
  'U': 'unity',
  'TTWO': 'take-two',
  'EA': 'ea',
  'ATVI': 'activisionblizzard',
  'QQQ': 'invesco',
  'SPY': 'spdr',
  'IWM': 'ishares',
  'DIA': 'spdr',
  'VTI': 'vanguard',
  'VOO': 'vanguard',
  'ARKK': 'ark-invest',
  'GLD': 'spdr',
  'SLV': 'ishares',
  'USO': 'uscf',
  'VIX': 'cboe',
  'BTC': 'bitcoin',
  'ETH': 'ethereum',
  'MARA': 'marathondigital',
  'RIOT': 'riotblockchain',
  'HOOD': 'robinhood',
  'SOFI': 'sofi',
  'AFRM': 'affirm',
  'UPST': 'upstart',
  'PATH': 'uipath',
  'AI': 'c3ai',
  'ARM': 'arm',
  'SMCI': 'supermicro',
  'AVGO': 'broadcom',
  'QCOM': 'qualcomm',
  'TXN': 'texasinstruments',
  'MU': 'micron',
  'LRCX': 'lamresearch',
  'AMAT': 'appliedmaterials',
  'KLAC': 'klacorporation',
  'ASML': 'asml',
  'TSM': 'tsmc',
};

export function getStockLogoUrl(symbol: string): string | null {
  if (!symbol) return null;
  
  const cleanSymbol = symbol.toUpperCase().replace(/[^A-Z]/g, '');
  
  const companyName = SYMBOL_COMPANY_MAP[cleanSymbol];
  
  if (companyName) {
    return `https://logo.clearbit.com/${companyName}.com`;
  }
  
  const commonDomains = [
    `${cleanSymbol.toLowerCase()}.com`,
    `${cleanSymbol.toLowerCase()}inc.com`,
    `${cleanSymbol.toLowerCase()}corp.com`,
  ];
  
  return `https://logo.clearbit.com/${commonDomains[0]}`;
}

export function getSymbolFallback(symbol: string): string {
  if (!symbol) return '?';
  return symbol.slice(0, 4).toUpperCase();
}
