// const symbols2 = [
//     // Forex Currency Pairs
//     "EURUSD",
//     "USDJPY",
//     "GBPUSD",
//     "AUDUSD",
//     "USDCAD",
//     "USDCHF",
//     "NZDUSD",
//     "EURJPY",
//     "GBPJPY",

//     // Cryptocurrencies (Single Coins)
//     "BTC",
//     "ETH",
//     "BNB",
//     "XRP",
//     "SOL",
//     "ADA",
//     "DOGE",
//     "AVAX",
//     "DOT",
//     "LTC",

//     // Crypto Pairs (Common Trading Pairs)
//     "BTCUSDT",
//     "ETHUSDT",
//     "BNBUSDT",
//     "SOLUSDT",
//     "ADAUSDT",
//     "DOGEUSDT",
//     "XRPUSDT",
//     "AVAXUSDT",
//     "ETHBTC",
//     "BNBBTC",
//     "LTCBTC",
//     "DOTUSDT",
//     "MATICUSDT",
//     "SHIBUSDT",

//     // Stocks (U.S. Stocks, using ticker symbols)
//     "AAPL",
//     "GOOGL",
//     "AMZN",
//     "MSFT",
//     "TSLA",
//     "META",
//     "NVDA",
//     "NFLX",
//     "JPM",
//     "BRK.B",
//     "V",
//     "UNH",
// ];

// const demo = [

//     // Forex
//     // { symbol: "EURUSD", market: "FOREX", curr: "Dollar" },
//     // { symbol: "USDJPY", market: "FOREX", curr: "Dollar" },
//     // { symbol: "GBPUSD", market: "FOREX", curr: "Dollar" },
//     // { symbol: "AUDUSD", market: "FOREX", curr: "Dollar" },
//     // { symbol: "USDCAD", market: "FOREX", curr: "Dollar" },
//     // { symbol: "USDCHF", market: "FOREX", curr: "Dollar" },
//     // { symbol: "NZDUSD", market: "FOREX", curr: "Dollar" },
//     // { symbol: "EURJPY", market: "FOREX", curr: "Yen" },
//     // { symbol: "GBPJPY", market: "FOREX", curr: "Yen" },

//     { symbol: "AUDCAD", market: "FOREX", curr: "Dollar" },
//     { symbol: "AUDCHF", market: "FOREX", curr: "Franc" },
//     { symbol: "AUDJPY", market: "FOREX", curr: "Yen" },
//     { symbol: "AUDNZD", market: "FOREX", curr: "Dollar" },
//     { symbol: "AUDUSD", market: "FOREX", curr: "Dollar" },
//     { symbol: "CADCHF", market: "FOREX", curr: "Franc" },
//     { symbol: "CADJPY", market: "FOREX", curr: "Yen" },
//     { symbol: "CHFJPY", market: "FOREX", curr: "Yen" },
//     { symbol: "EURAUD", market: "FOREX", curr: "Dollar" },
//     { symbol: "EURCAD", market: "FOREX", curr: "Dollar" },
//     { symbol: "EURCHF", market: "FOREX", curr: "Franc" },
//     { symbol: "EURGBP", market: "FOREX", curr: "Pound" },
//     { symbol: "EURHKD", market: "FOREX", curr: "Dollar" },
//     { symbol: "EURJPY", market: "FOREX", curr: "Yen" },
//     { symbol: "EURNOK", market: "FOREX", curr: "Krone" },
//     { symbol: "EURNZD", market: "FOREX", curr: "Dollar" },
//     { symbol: "EURPLN", market: "FOREX", curr: "Zloty" },
//     { symbol: "EURSEK", market: "FOREX", curr: "Krona" },
//     { symbol: "EURTRY", market: "FOREX", curr: "Lira" },
//     { symbol: "EURUSD", market: "FOREX", curr: "Dollar" },
//     { symbol: "GBPAUD", market: "FOREX", curr: "Dollar" },
//     { symbol: "GBPCAD", market: "FOREX", curr: "Dollar" },
//     { symbol: "GBPCHF", market: "FOREX", curr: "Franc" },
//     { symbol: "GBPJPY", market: "FOREX", curr: "Yen" },
//     { symbol: "GBPNZD", market: "FOREX", curr: "Dollar" },
//     { symbol: "GBPPLN", market: "FOREX", curr: "Zloty" },
//     { symbol: "GBPSEK", market: "FOREX", curr: "Krona" },
//     { symbol: "GBPUSD", market: "FOREX", curr: "Dollar" },
//     { symbol: "NZDCAD", market: "FOREX", curr: "Dollar" },
//     { symbol: "NZDCHF", market: "FOREX", curr: "Franc" },
//     { symbol: "NZDJPY", market: "FOREX", curr: "Yen" },
//     { symbol: "NZDUSD", market: "FOREX", curr: "Dollar" },
//     { symbol: "USDCAD", market: "FOREX", curr: "Dollar" },
//     { symbol: "USDCHF", market: "FOREX", curr: "Franc" },
//     { symbol: "USDCZK", market: "FOREX", curr: "Koruna" },
//     { symbol: "USDHKD", market: "FOREX", curr: "Dollar" },
//     { symbol: "USDHUF", market: "FOREX", curr: "Forint" },
//     { symbol: "USDJPY", market: "FOREX", curr: "Yen" },
//     { symbol: "USDMXN", market: "FOREX", curr: "Peso" },
//     { symbol: "USDNOK", market: "FOREX", curr: "Krone" },
//     { symbol: "USDPLN", market: "FOREX", curr: "Zloty" },
//     { symbol: "USDSEK", market: "FOREX", curr: "Krona" },
//     { symbol: "USDSGD", market: "FOREX", curr: "Dollar" },
//     { symbol: "USDTRY", market: "FOREX", curr: "Lira" },
//     { symbol: "USDZAR", market: "FOREX", curr: "Rand" },
//     { symbol: "XAGUSD", market: "FOREX", curr: "Dollar" },
//     { symbol: "XAUEUR", market: "FOREX", curr: "Euro" },
//     { symbol: "XAUUSD", market: "FOREX", curr: "Dollar" },

//     // Crypto Pairs
//     { symbol: "BTCUSDT", market: "CRYPTO", curr: "Dollar" },
//     { symbol: "ETHUSDT", market: "CRYPTO", curr: "Dollar" },
//     { symbol: "BNBUSDT", market: "CRYPTO", curr: "Dollar" },
//     { symbol: "SOLUSDT", market: "CRYPTO", curr: "Dollar" },
//     { symbol: "ADAUSDT", market: "CRYPTO", curr: "Dollar" },
//     { symbol: "DOGEUSDT", market: "CRYPTO", curr: "Dollar" },
//     { symbol: "XRPUSDT", market: "CRYPTO", curr: "Dollar" },
//     { symbol: "AVAXUSDT", market: "CRYPTO", curr: "Dollar" },
//     { symbol: "ETHBTC", market: "CRYPTO", curr: "Bitcoin" },
//     { symbol: "BNBBTC", market: "CRYPTO", curr: "Bitcoin" },
//     { symbol: "LTCBTC", market: "CRYPTO", curr: "Bitcoin" },
//     { symbol: "DOTUSDT", market: "CRYPTO", curr: "Dollar" },
//     { symbol: "MATICUSDT", market: "CRYPTO", curr: "Dollar" },
//     { symbol: "SHIBUSDT", market: "CRYPTO", curr: "Dollar" },

//     // Stocks
//     { symbol: "AAPL", market: "STOCK", curr: "USD" },
//     { symbol: "GOOGL", market: "STOCK", curr: "USD" },
//     { symbol: "AMZN", market: "STOCK", curr: "USD" },
//     { symbol: "MSFT", market: "STOCK", curr: "USD" },
//     { symbol: "TSLA", market: "STOCK", curr: "USD" },
//     { symbol: "META", market: "STOCK", curr: "USD" },
//     { symbol: "NVDA", market: "STOCK", curr: "USD" },
//     { symbol: "NFLX", market: "STOCK", curr: "USD" },
//     { symbol: "JPM", market: "STOCK", curr: "USD" },
//     { symbol: "BRK.B", market: "STOCK", curr: "USD" },
//     { symbol: "V", market: "STOCK", curr: "USD" },
//     { symbol: "UNH", market: "STOCK", curr: "USD" },

// ];

// const symbols = [
//     // Forex Pairs
//     { symbol: "AUDCAD", market: "FOREX", curr: "Dollar", name: "Australian Dollar vs Canadian Dollar" },
//     { symbol: "AUDCHF", market: "FOREX", curr: "Franc", name: "Australian Dollar vs Swiss Franc" },
//     { symbol: "AUDJPY", market: "FOREX", curr: "Yen", name: "Australian Dollar vs Japanese Yen" },
//     { symbol: "AUDNZD", market: "FOREX", curr: "Dollar", name: "Australian Dollar vs New Zealand Dollar" },
//     { symbol: "AUDUSD", market: "FOREX", curr: "Dollar", name: "Australian Dollar vs US Dollar" },
//     { symbol: "CADCHF", market: "FOREX", curr: "Franc", name: "Canadian Dollar vs Swiss Franc" },
//     { symbol: "CADJPY", market: "FOREX", curr: "Yen", name: "Canadian Dollar vs Japanese Yen" },
//     { symbol: "CHFJPY", market: "FOREX", curr: "Yen", name: "Swiss Franc vs Japanese Yen" },
//     { symbol: "EURAUD", market: "FOREX", curr: "Dollar", name: "Euro vs Australian Dollar" },
//     { symbol: "EURCAD", market: "FOREX", curr: "Dollar", name: "Euro vs Canadian Dollar" },
//     { symbol: "EURCHF", market: "FOREX", curr: "Franc", name: "Euro vs Swiss Franc" },
//     { symbol: "EURGBP", market: "FOREX", curr: "Pound", name: "Euro vs British Pound" },
//     { symbol: "EURHKD", market: "FOREX", curr: "Dollar", name: "Euro vs Hong Kong Dollar" },
//     { symbol: "EURJPY", market: "FOREX", curr: "Yen", name: "Euro vs Japanese Yen" },
//     { symbol: "EURNOK", market: "FOREX", curr: "Krone", name: "Euro vs Norwegian Krone" },
//     { symbol: "EURNZD", market: "FOREX", curr: "Dollar", name: "Euro vs New Zealand Dollar" },
//     { symbol: "EURPLN", market: "FOREX", curr: "Zloty", name: "Euro vs Polish Złoty" },
//     { symbol: "EURSEK", market: "FOREX", curr: "Krona", name: "Euro vs Swedish Krona" },
//     { symbol: "EURTRY", market: "FOREX", curr: "Lira", name: "Euro vs Turkish Lira" },
//     { symbol: "EURUSD", market: "FOREX", curr: "Dollar", name: "Euro vs US Dollar" },
//     { symbol: "GBPAUD", market: "FOREX", curr: "Dollar", name: "British Pound vs Australian Dollar" },
//     { symbol: "GBPCAD", market: "FOREX", curr: "Dollar", name: "British Pound vs Canadian Dollar" },
//     { symbol: "GBPCHF", market: "FOREX", curr: "Franc", name: "British Pound vs Swiss Franc" },
//     { symbol: "GBPJPY", market: "FOREX", curr: "Yen", name: "British Pound vs Japanese Yen" },
//     { symbol: "GBPNZD", market: "FOREX", curr: "Dollar", name: "British Pound vs New Zealand Dollar" },
//     { symbol: "GBPPLN", market: "FOREX", curr: "Zloty", name: "British Pound vs Polish Złoty" },
//     { symbol: "GBPSEK", market: "FOREX", curr: "Krona", name: "British Pound vs Swedish Krona" },
//     { symbol: "GBPUSD", market: "FOREX", curr: "Dollar", name: "British Pound vs US Dollar" },
//     { symbol: "NZDCAD", market: "FOREX", curr: "Dollar", name: "New Zealand Dollar vs Canadian Dollar" },
//     { symbol: "NZDCHF", market: "FOREX", curr: "Franc", name: "New Zealand Dollar vs Swiss Franc" },
//     { symbol: "NZDJPY", market: "FOREX", curr: "Yen", name: "New Zealand Dollar vs Japanese Yen" },
//     { symbol: "NZDUSD", market: "FOREX", curr: "Dollar", name: "New Zealand Dollar vs US Dollar" },
//     { symbol: "USDCAD", market: "FOREX", curr: "Dollar", name: "US Dollar vs Canadian Dollar" },
//     { symbol: "USDCHF", market: "FOREX", curr: "Franc", name: "US Dollar vs Swiss Franc" },
//     { symbol: "USDCZK", market: "FOREX", curr: "Koruna", name: "US Dollar vs Czech Koruna" },
//     { symbol: "USDHKD", market: "FOREX", curr: "Dollar", name: "US Dollar vs Hong Kong Dollar" },
//     { symbol: "USDHUF", market: "FOREX", curr: "Forint", name: "US Dollar vs Hungarian Forint" },
//     { symbol: "USDJPY", market: "FOREX", curr: "Yen", name: "US Dollar vs Japanese Yen" },
//     { symbol: "USDMXN", market: "FOREX", curr: "Peso", name: "US Dollar vs Mexican Peso" },
//     { symbol: "USDNOK", market: "FOREX", curr: "Krone", name: "US Dollar vs Norwegian Krone" },
//     { symbol: "USDPLN", market: "FOREX", curr: "Zloty", name: "US Dollar vs Polish Złoty" },
//     { symbol: "USDSEK", market: "FOREX", curr: "Krona", name: "US Dollar vs Swedish Krona" },
//     { symbol: "USDSGD", market: "FOREX", curr: "Dollar", name: "US Dollar vs Singapore Dollar" },
//     { symbol: "USDTRY", market: "FOREX", curr: "Lira", name: "US Dollar vs Turkish Lira" },
//     { symbol: "USDZAR", market: "FOREX", curr: "Rand", name: "US Dollar vs South African Rand" },
//     { symbol: "XAGUSD", market: "FOREX", curr: "Dollar", name: "Silver vs US Dollar" },
//     { symbol: "XAUEUR", market: "FOREX", curr: "Euro", name: "Gold vs Euro" },
//     { symbol: "XAUUSD", market: "FOREX", curr: "Dollar", name: "Gold vs US Dollar" },

// ];
type ForexSymbol={
    
    symbol:string;
    market:string;
    curr:string;
    name:string;
    conversionRate:number |null;
}

const symbols:ForexSymbol[] = [
    // Forex Pairs
    { symbol: "AUDCAD", market: "FOREX", curr: "Dollar", name: "Australian Dollar vs Canadian Dollar", conversionRate: 0.90 },
    { symbol: "AUDCHF", market: "FOREX", curr: "Franc", name: "Australian Dollar vs Swiss Franc", conversionRate: 0.68 },
    { symbol: "AUDJPY", market: "FOREX", curr: "Yen", name: "Australian Dollar vs Japanese Yen", conversionRate: 0.0067 },
    { symbol: "AUDNZD", market: "FOREX", curr: "Dollar", name: "Australian Dollar vs New Zealand Dollar", conversionRate: 0.62 },
    { symbol: "AUDUSD", market: "FOREX", curr: "Dollar", name: "Australian Dollar vs US Dollar", conversionRate: 1 },
    { symbol: "CADCHF", market: "FOREX", curr: "Franc", name: "Canadian Dollar vs Swiss Franc", conversionRate: 0.76 },
    { symbol: "CADJPY", market: "FOREX", curr: "Yen", name: "Canadian Dollar vs Japanese Yen", conversionRate: 0.0074 },
    { symbol: "CHFJPY", market: "FOREX", curr: "Yen", name: "Swiss Franc vs Japanese Yen", conversionRate: 0.0067 },
    { symbol: "EURAUD", market: "FOREX", curr: "Dollar", name: "Euro vs Australian Dollar", conversionRate: 0.67 },
    { symbol: "EURCAD", market: "FOREX", curr: "Dollar", name: "Euro vs Canadian Dollar", conversionRate: 0.75 },
    { symbol: "EURCHF", market: "FOREX", curr: "Franc", name: "Euro vs Swiss Franc", conversionRate: 1.10 },
    { symbol: "EURGBP", market: "FOREX", curr: "Pound", name: "Euro vs British Pound", conversionRate: 1.25 },
    { symbol: "EURHKD", market: "FOREX", curr: "Dollar", name: "Euro vs Hong Kong Dollar", conversionRate: 0.13 },
    { symbol: "EURJPY", market: "FOREX", curr: "Yen", name: "Euro vs Japanese Yen", conversionRate: 0.0067 },
    { symbol: "EURNOK", market: "FOREX", curr: "Krone", name: "Euro vs Norwegian Krone", conversionRate: 0.095 },
    { symbol: "EURNZD", market: "FOREX", curr: "Dollar", name: "Euro vs New Zealand Dollar", conversionRate: 0.61 },
    { symbol: "EURPLN", market: "FOREX", curr: "Zloty", name: "Euro vs Polish Złoty", conversionRate: 0.25 },
    { symbol: "EURSEK", market: "FOREX", curr: "Krona", name: "Euro vs Swedish Krona", conversionRate: 0.095 },
    { symbol: "EURTRY", market: "FOREX", curr: "Lira", name: "Euro vs Turkish Lira", conversionRate: 0.031 },
    { symbol: "EURUSD", market: "FOREX", curr: "Dollar", name: "Euro vs US Dollar", conversionRate: 1 },
    { symbol: "GBPAUD", market: "FOREX", curr: "Dollar", name: "British Pound vs Australian Dollar", conversionRate: 0.67 },
    { symbol: "GBPCAD", market: "FOREX", curr: "Dollar", name: "British Pound vs Canadian Dollar", conversionRate: 0.75 },
    { symbol: "GBPCHF", market: "FOREX", curr: "Franc", name: "British Pound vs Swiss Franc", conversionRate: 1.10 },
    { symbol: "GBPJPY", market: "FOREX", curr: "Yen", name: "British Pound vs Japanese Yen", conversionRate: 0.0067 },
    { symbol: "GBPNZD", market: "FOREX", curr: "Dollar", name: "British Pound vs New Zealand Dollar", conversionRate: 0.61 },
    { symbol: "GBPPLN", market: "FOREX", curr: "Zloty", name: "British Pound vs Polish Złoty", conversionRate: 0.25 },
    { symbol: "GBPSEK", market: "FOREX", curr: "Krona", name: "British Pound vs Swedish Krona", conversionRate: 0.095 },
    { symbol: "GBPUSD", market: "FOREX", curr: "Dollar", name: "British Pound vs US Dollar", conversionRate: 1 },
    { symbol: "NZDCAD", market: "FOREX", curr: "Dollar", name: "New Zealand Dollar vs Canadian Dollar", conversionRate: 0.75 },
    { symbol: "NZDCHF", market: "FOREX", curr: "Franc", name: "New Zealand Dollar vs Swiss Franc", conversionRate: 1.10 },
    { symbol: "NZDJPY", market: "FOREX", curr: "Yen", name: "New Zealand Dollar vs Japanese Yen", conversionRate: 0.0067 },
    { symbol: "NZDUSD", market: "FOREX", curr: "Dollar", name: "New Zealand Dollar vs US Dollar", conversionRate: 1 },
    { symbol: "USDCAD", market: "FOREX", curr: "Dollar", name: "US Dollar vs Canadian Dollar", conversionRate: null },
    { symbol: "USDCHF", market: "FOREX", curr: "Franc", name: "US Dollar vs Swiss Franc", conversionRate: null },
    { symbol: "USDCZK", market: "FOREX", curr: "Koruna", name: "US Dollar vs Czech Koruna", conversionRate: null },
    { symbol: "USDHKD", market: "FOREX", curr: "Dollar", name: "US Dollar vs Hong Kong Dollar", conversionRate: null },
    { symbol: "USDHUF", market: "FOREX", curr: "Forint", name: "US Dollar vs Hungarian Forint", conversionRate: null },
    { symbol: "USDJPY", market: "FOREX", curr: "Yen", name: "US Dollar vs Japanese Yen", conversionRate: null },
    { symbol: "USDMXN", market: "FOREX", curr: "Peso", name: "US Dollar vs Mexican Peso", conversionRate: null },
    { symbol: "USDNOK", market: "FOREX", curr: "Krone", name: "US Dollar vs Norwegian Krone", conversionRate: null },
    { symbol: "USDPLN", market: "FOREX", curr: "Zloty", name: "US Dollar vs Polish Złoty", conversionRate: null },
    { symbol: "USDSEK", market: "FOREX", curr: "Krona", name: "US Dollar vs Swedish Krona", conversionRate: null },
    { symbol: "USDSGD", market: "FOREX", curr: "Dollar", name: "US Dollar vs Singapore Dollar", conversionRate: null },
    { symbol: "USDTRY", market: "FOREX", curr: "Lira", name: "US Dollar vs Turkish Lira", conversionRate: null },
    { symbol: "USDZAR", market: "FOREX", curr: "Rand", name: "US Dollar vs South African Rand", conversionRate: null },
    { symbol: "XAGUSD", market: "FOREX", curr: "Dollar", name: "Silver vs US Dollar", conversionRate: 1 },
    { symbol: "XAUEUR", market: "FOREX", curr: "Euro", name: "Gold vs Euro", conversionRate: 1.08 },
    { symbol: "XAUUSD", market: "FOREX", curr: "Dollar", name: "Gold vs US Dollar", conversionRate: 1 },
];

export default symbols;