export const demoAccount = {
  id: 'demo-account',
  _id: 'demo-account',
  name: 'Demo Account',
  accountName: 'Demo Account',
  balance: 10000,
  broker: 'Paper Trading',
  isPropFirm: false,
  currency: 'USD',
  checked: true,
  createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
};

// Generate demo trades dynamically to ensure they appear in current and previous month
function generateDemoTrades() {
  const now = Date.now();
  const day = 24 * 60 * 60 * 1000;
  
  // Get first day of current month and previous month
  const today = new Date();
  const firstOfMonth = new Date(today.getFullYear(), today.getMonth(), 1);
  const firstOfPrevMonth = new Date(today.getFullYear(), today.getMonth() - 1, 1);
  
  // Spread trades across both December 2025 and January 2026
  return [
    // December 2025 trades (previous month)
    {
      id: 'demo-trade-dec-1',
      _id: 'demo-trade-dec-1',
      accountId: 'demo-account',
      symbol: 'EURUSD',
      side: 'long',
      entryPrice: 1.0820,
      exitPrice: 1.0865,
      quantity: 1.5,
      pnl: 675,
      status: 'closed',
      entryDate: new Date(firstOfPrevMonth.getTime() + 10 * day).toISOString(),
      exitDate: new Date(firstOfPrevMonth.getTime() + 10 * day + 5 * 60 * 60 * 1000).toISOString(),
      riskRewardRatio: 2.3,
      notes: 'Trend following on EUR strength',
    },
    {
      id: 'demo-trade-dec-2',
      _id: 'demo-trade-dec-2',
      accountId: 'demo-account',
      symbol: 'BTCUSD',
      side: 'long',
      entryPrice: 41800,
      exitPrice: 42600,
      quantity: 0.4,
      pnl: 320,
      status: 'closed',
      entryDate: new Date(firstOfPrevMonth.getTime() + 12 * day).toISOString(),
      exitDate: new Date(firstOfPrevMonth.getTime() + 12 * day + 8 * 60 * 60 * 1000).toISOString(),
      riskRewardRatio: 1.9,
      notes: 'Bitcoin momentum breakout',
    },
    {
      id: 'demo-trade-dec-3',
      _id: 'demo-trade-dec-3',
      accountId: 'demo-account',
      symbol: 'AAPL',
      side: 'short',
      entryPrice: 182.50,
      exitPrice: 184.20,
      quantity: 40,
      pnl: -68,
      status: 'closed',
      entryDate: new Date(firstOfPrevMonth.getTime() + 15 * day).toISOString(),
      exitDate: new Date(firstOfPrevMonth.getTime() + 15 * day + 3 * 60 * 60 * 1000).toISOString(),
      riskRewardRatio: 0.5,
      notes: 'Counter-trend short failed',
    },
    {
      id: 'demo-trade-dec-4',
      _id: 'demo-trade-dec-4',
      accountId: 'demo-account',
      symbol: 'XAUUSD',
      side: 'long',
      entryPrice: 2008.00,
      exitPrice: 2028.50,
      quantity: 0.6,
      pnl: 1230,
      status: 'closed',
      entryDate: new Date(firstOfPrevMonth.getTime() + 18 * day).toISOString(),
      exitDate: new Date(firstOfPrevMonth.getTime() + 19 * day).toISOString(),
      riskRewardRatio: 2.8,
      notes: 'Gold rally on rate cut expectations',
    },
    {
      id: 'demo-trade-dec-5',
      _id: 'demo-trade-dec-5',
      accountId: 'demo-account',
      symbol: 'GBPUSD',
      side: 'short',
      entryPrice: 1.2720,
      exitPrice: 1.2680,
      quantity: 1.0,
      pnl: 400,
      status: 'closed',
      entryDate: new Date(firstOfPrevMonth.getTime() + 20 * day).toISOString(),
      exitDate: new Date(firstOfPrevMonth.getTime() + 20 * day + 6 * 60 * 60 * 1000).toISOString(),
      riskRewardRatio: 2.0,
      notes: 'GBP weakness on BOE comments',
    },
    {
      id: 'demo-trade-dec-6',
      _id: 'demo-trade-dec-6',
      accountId: 'demo-account',
      symbol: 'TSLA',
      side: 'long',
      entryPrice: 238.00,
      exitPrice: 235.50,
      quantity: 25,
      pnl: -62.5,
      status: 'closed',
      entryDate: new Date(firstOfPrevMonth.getTime() + 22 * day).toISOString(),
      exitDate: new Date(firstOfPrevMonth.getTime() + 22 * day + 2 * 60 * 60 * 1000).toISOString(),
      riskRewardRatio: 0.4,
      notes: 'Stopped out on gap down',
    },
    {
      id: 'demo-trade-dec-7',
      _id: 'demo-trade-dec-7',
      accountId: 'demo-account',
      symbol: 'NVDA',
      side: 'long',
      entryPrice: 478.00,
      exitPrice: 495.50,
      quantity: 15,
      pnl: 262.5,
      status: 'closed',
      entryDate: new Date(firstOfPrevMonth.getTime() + 26 * day).toISOString(),
      exitDate: new Date(firstOfPrevMonth.getTime() + 27 * day).toISOString(),
      riskRewardRatio: 2.1,
      notes: 'AI chip demand surge',
    },
    {
      id: 'demo-trade-dec-8',
      _id: 'demo-trade-dec-8',
      accountId: 'demo-account',
      symbol: 'EURUSD',
      side: 'short',
      entryPrice: 1.0880,
      exitPrice: 1.0845,
      quantity: 2.0,
      pnl: 700,
      status: 'closed',
      entryDate: new Date(firstOfPrevMonth.getTime() + 28 * day).toISOString(),
      exitDate: new Date(firstOfPrevMonth.getTime() + 28 * day + 4 * 60 * 60 * 1000).toISOString(),
      riskRewardRatio: 1.8,
      notes: 'Year-end EUR selling',
    },
    // January 2026 trades (current month)
    {
      id: 'demo-trade-1',
      _id: 'demo-trade-1',
      accountId: 'demo-account',
      symbol: 'EURUSD',
      side: 'long',
      entryPrice: 1.0850,
      exitPrice: 1.0892,
      quantity: 1.0,
      pnl: 420,
      status: 'closed',
      entryDate: new Date(firstOfMonth.getTime() + 1 * day).toISOString(),
      exitDate: new Date(firstOfMonth.getTime() + 1 * day + 4 * 60 * 60 * 1000).toISOString(),
      riskRewardRatio: 2.1,
      notes: 'Clean breakout trade with strong momentum',
    },
    {
      id: 'demo-trade-2',
      _id: 'demo-trade-2',
      accountId: 'demo-account',
      symbol: 'BTCUSD',
      side: 'long',
      entryPrice: 42500,
      exitPrice: 43200,
      quantity: 0.5,
      pnl: 350,
      status: 'closed',
      entryDate: new Date(firstOfMonth.getTime() + 1 * day + 6 * 60 * 60 * 1000).toISOString(),
      exitDate: new Date(firstOfMonth.getTime() + 1 * day + 12 * 60 * 60 * 1000).toISOString(),
      riskRewardRatio: 1.8,
      notes: 'Followed the trend after consolidation',
    },
    {
      id: 'demo-trade-3',
      _id: 'demo-trade-3',
      accountId: 'demo-account',
      symbol: 'AAPL',
      side: 'long',
      entryPrice: 185.20,
      exitPrice: 183.50,
      quantity: 50,
      pnl: -85,
      status: 'closed',
      entryDate: new Date(firstOfMonth.getTime() + 2 * day).toISOString(),
      exitDate: new Date(firstOfMonth.getTime() + 2 * day + 2 * 60 * 60 * 1000).toISOString(),
      riskRewardRatio: 0.4,
      notes: 'Stopped out on false breakout',
    },
    {
      id: 'demo-trade-4',
      _id: 'demo-trade-4',
      accountId: 'demo-account',
      symbol: 'EURUSD',
      side: 'short',
      entryPrice: 1.0920,
      exitPrice: 1.0878,
      quantity: 1.5,
      pnl: 630,
      status: 'closed',
      entryDate: new Date(firstOfMonth.getTime() + 2 * day + 4 * 60 * 60 * 1000).toISOString(),
      exitDate: new Date(firstOfMonth.getTime() + 2 * day + 9 * 60 * 60 * 1000).toISOString(),
      riskRewardRatio: 2.5,
      notes: 'Reversal pattern at resistance',
    },
    {
      id: 'demo-trade-5',
      _id: 'demo-trade-5',
      accountId: 'demo-account',
      symbol: 'GBPUSD',
      side: 'long',
      entryPrice: 1.2650,
      exitPrice: 1.2720,
      quantity: 1.0,
      pnl: 700,
      status: 'closed',
      entryDate: new Date(firstOfMonth.getTime() + 3 * day).toISOString(),
      exitDate: new Date(firstOfMonth.getTime() + 3 * day + 8 * 60 * 60 * 1000).toISOString(),
      riskRewardRatio: 2.3,
      notes: 'Swing trade on daily support bounce',
    },
    {
      id: 'demo-trade-6',
      _id: 'demo-trade-6',
      accountId: 'demo-account',
      symbol: 'BTCUSD',
      side: 'short',
      entryPrice: 44200,
      exitPrice: 44800,
      quantity: 0.3,
      pnl: -180,
      status: 'closed',
      entryDate: new Date(firstOfMonth.getTime() + 3 * day + 4 * 60 * 60 * 1000).toISOString(),
      exitDate: new Date(firstOfMonth.getTime() + 3 * day + 7 * 60 * 60 * 1000).toISOString(),
      riskRewardRatio: 0.6,
      notes: 'Counter-trend trade failed',
    },
    {
      id: 'demo-trade-7',
      _id: 'demo-trade-7',
      accountId: 'demo-account',
      symbol: 'TSLA',
      side: 'long',
      entryPrice: 242.50,
      exitPrice: 251.80,
      quantity: 20,
      pnl: 186,
      status: 'closed',
      entryDate: new Date(firstOfMonth.getTime() + 4 * day).toISOString(),
      exitDate: new Date(firstOfMonth.getTime() + 4 * day + 6 * 60 * 60 * 1000).toISOString(),
      riskRewardRatio: 1.9,
      notes: 'Earnings momentum play',
    },
    {
      id: 'demo-trade-8',
      _id: 'demo-trade-8',
      accountId: 'demo-account',
      symbol: 'EURUSD',
      side: 'long',
      entryPrice: 1.0810,
      exitPrice: 1.0845,
      quantity: 2.0,
      pnl: 700,
      status: 'closed',
      entryDate: new Date(firstOfMonth.getTime() + 4 * day + 4 * 60 * 60 * 1000).toISOString(),
      exitDate: new Date(firstOfMonth.getTime() + 4 * day + 8 * 60 * 60 * 1000).toISOString(),
      riskRewardRatio: 1.7,
      notes: 'News-driven spike entry',
    },
    {
      id: 'demo-trade-9',
      _id: 'demo-trade-9',
      accountId: 'demo-account',
      symbol: 'AAPL',
      side: 'short',
      entryPrice: 188.40,
      exitPrice: 190.20,
      quantity: 30,
      pnl: -54,
      status: 'closed',
      entryDate: new Date(Math.min(firstOfMonth.getTime() + 5 * day, now - day)).toISOString(),
      exitDate: new Date(Math.min(firstOfMonth.getTime() + 5 * day + 1 * 60 * 60 * 1000, now - day + 1 * 60 * 60 * 1000)).toISOString(),
      riskRewardRatio: 0.3,
      notes: 'Premature short entry',
    },
    {
      id: 'demo-trade-10',
      _id: 'demo-trade-10',
      accountId: 'demo-account',
      symbol: 'XAUUSD',
      side: 'long',
      entryPrice: 2015.50,
      exitPrice: 2042.30,
      quantity: 0.5,
      pnl: 1340,
      status: 'closed',
      entryDate: new Date(Math.min(firstOfMonth.getTime() + 5 * day + 4 * 60 * 60 * 1000, now - day + 4 * 60 * 60 * 1000)).toISOString(),
      exitDate: new Date(Math.min(firstOfMonth.getTime() + 5 * day + 10 * 60 * 60 * 1000, now - day + 10 * 60 * 60 * 1000)).toISOString(),
      riskRewardRatio: 3.2,
      notes: 'Gold breakout on safe-haven flow',
    },
    {
      id: 'demo-trade-11',
      _id: 'demo-trade-11',
      accountId: 'demo-account',
      symbol: 'BTCUSD',
      side: 'long',
      entryPrice: 43800,
      exitPrice: 45100,
      quantity: 0.4,
      pnl: 520,
      status: 'closed',
      entryDate: new Date(now - 2 * day).toISOString(),
      exitDate: new Date(now - 2 * day + 8 * 60 * 60 * 1000).toISOString(),
      riskRewardRatio: 2.6,
      notes: 'Trend continuation after pullback',
    },
    {
      id: 'demo-trade-12',
      _id: 'demo-trade-12',
      accountId: 'demo-account',
      symbol: 'EURUSD',
      side: 'short',
      entryPrice: 1.0890,
      exitPrice: 1.0920,
      quantity: 1.0,
      pnl: -300,
      status: 'closed',
      entryDate: new Date(now - 1 * day).toISOString(),
      exitDate: new Date(now - 1 * day + 2 * 60 * 60 * 1000).toISOString(),
      riskRewardRatio: 0.5,
      notes: 'Wrong direction on NFP',
    },
    {
      id: 'demo-trade-13',
      _id: 'demo-trade-13',
      accountId: 'demo-account',
      symbol: 'NVDA',
      side: 'long',
      entryPrice: 485.20,
      exitPrice: 502.80,
      quantity: 10,
      pnl: 176,
      status: 'closed',
      entryDate: new Date(now - 1 * day + 4 * 60 * 60 * 1000).toISOString(),
      exitDate: new Date(now - 1 * day + 10 * 60 * 60 * 1000).toISOString(),
      riskRewardRatio: 2.2,
      notes: 'AI sector momentum',
    },
    {
      id: 'demo-trade-14',
      _id: 'demo-trade-14',
      accountId: 'demo-account',
      symbol: 'GBPUSD',
      side: 'long',
      entryPrice: 1.2680,
      exitPrice: 1.2735,
      quantity: 1.2,
      pnl: 660,
      status: 'closed',
      entryDate: new Date(now - 12 * 60 * 60 * 1000).toISOString(),
      exitDate: new Date(now - 6 * 60 * 60 * 1000).toISOString(),
      riskRewardRatio: 1.8,
      notes: 'Support level bounce',
    },
    {
      id: 'demo-trade-15',
      _id: 'demo-trade-15',
      accountId: 'demo-account',
      symbol: 'XAUUSD',
      side: 'short',
      entryPrice: 2048.00,
      exitPrice: 2055.50,
      quantity: 0.3,
      pnl: -225,
      status: 'closed',
      entryDate: new Date(now - 6 * 60 * 60 * 1000).toISOString(),
      exitDate: new Date(now - 4 * 60 * 60 * 1000).toISOString(),
      riskRewardRatio: 0.4,
      notes: 'Faded breakout too early',
    },
  ];
}

export const demoTrades = generateDemoTrades();

export const demoDashboardStats = {
  totalPnl: 4838,
  winRate: 60,
  avgRRR: 1.62,
  totalTrades: 15,
  winningTrades: 9,
  losingTrades: 6,
  avgWin: 520.22,
  avgLoss: 140.67,
  largestWin: 1340,
  largestLoss: -300,
  profitFactor: 2.21,
  expectancy: 322.53,
  currentStreak: 2,
  maxDrawdown: -619,
  bestDay: 1340,
  worstDay: -300,
};

// Demo account with embedded trade data for dashboard rendering
export const demoAccountWithTrades = {
  ...demoAccount,
  tradeData: demoTrades.map(trade => ({
    // Convert ISO date to YYYY-MM-DD format for calendar matching
    date: trade.entryDate.split('T')[0],
    Profit: trade.pnl,
    Item: trade.symbol,
    Currency: 'USD',
    side: trade.side,
    entryPrice: trade.entryPrice,
    exitPrice: trade.exitPrice,
    quantity: trade.quantity,
    notes: trade.notes,
    riskRewardRatio: trade.riskRewardRatio,
    status: trade.status,
  })),
};

export const demoAccounts = [demoAccountWithTrades];

export function isDemoMode(userId: string | undefined): boolean {
  return userId === 'demo-user';
}
